import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "secondary-container": "#25ad00",
        "surface-container-low": "#171c25",
        "on-primary-fixed": "#121f00",
        "tertiary-container": "#6dfe9c",
        error: "#ffb4ab",
        "on-tertiary-container": "#007439",
        "surface-container-lowest": "#0a0e17",
        tertiary: "#ffffff",
        secondary: "#5fe140",
        "secondary-fixed": "#7cff5b",
        "primary-fixed": "#aff833",
        "surface-container": "#1b2029",
        "on-error": "#690005",
        "surface-container-high": "#262a34",
        "on-error-container": "#ffdad6",
        "surface-variant": "#31353f",
        "error-container": "#93000a",
        "primary-container": "#aff833",
        background: "#0f131d",
        "on-tertiary-fixed-variant": "#005227",
        "secondary-fixed-dim": "#5fe140",
        "inverse-on-surface": "#2c303b",
        "on-tertiary": "#003919",
        "on-secondary-container": "#063700",
        "primary-fixed-dim": "#95da03",
        surface: "#0f131d",
        primary: "#ffffff",
        "on-surface": "#dfe2f0",
        "inverse-surface": "#dfe2f0",
        "on-secondary": "#063900",
        "tertiary-fixed": "#6dfe9c",
        "surface-tint": "#95da03",
        "on-primary-fixed-variant": "#334f00",
        "on-tertiary-fixed": "#00210c",
        "on-surface-variant": "#c2caaf",
        "on-primary-container": "#4a6f00",
        "tertiary-fixed-dim": "#4de082",
        "on-secondary-fixed": "#022100",
        "on-secondary-fixed-variant": "#0d5300",
        "outline-variant": "#424935",
        outline: "#8c947b",
        "inverse-primary": "#456800",
        "surface-container-highest": "#31353f",
        "surface-dim": "#0f131d",
        "surface-bright": "#353944",
        "on-background": "#dfe2f0",
        "on-primary": "#223600",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "2xl": "48px",
        base: "8px",
        lg: "24px",
        "margin-mobile": "16px",
        xl: "32px",
        sm: "8px",
        md: "16px",
        xs: "4px",
        "margin-desktop": "40px",
        gutter: "24px",
      },
    },
  },
  plugins: [],
};
export default config;
